### ISSUE TITLE
Image URLs drop commas

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#20]
Noticed in talking about #12  that the most recent mapping strips commas from the URL in ImagePath so `https://iiif.museum.colby.edu/image/2013.003_001/full/512,/0/default.jpg` (resolvable) becomes `https://iiif.museum.colby.edu/image/2013.003_001/full/512/0/default.jpg` (sad trombone).

**Comment by workergnome** [comment]
Oh, boo.  That's not good.

**Comment by bsnikhila** [comment]
Since the URL itself is being used as the URI, all characters unsafe for the URI, including commas, are removed when generating the triples. So I am using the URI as:
https://iiif.museum.colby.edu/image/2013.003_001/full/full/0/default.jpg
instead of 
https://iiif.museum.colby.edu/image/2013.003_001/full/512,/0/default.jpg

The parameter is changed from "512," to "full", so that the URL can be dereferenced.

**Comment by workergnome** [comment]
The issue is that commas ARE valid for urls, at least in that position.  And they're mandated for IIIF urls. 
Also, if there are invalid characters, the correct response is to percent-encode them, not drop them.

**Comment by caknoblock** [comment]
Commas are certainly valid for URLs, but Karma does not permit them within a URI.  In this case you are using the URI as the URL, so it creates a problem.  Since we cannot support the comma in the URI, we either need to drop the commas or we need to define a separate URI and URL.  Nikhila’s proposal is a short term fix that will allow us to make progress while we figure out the general solution to this issue.

**Comment by azaroth42** [comment]
That seems like a bug in Karma to reject valid URIs (that happen to be URLs). Could you have a post-processing step that replaces a URI invalid character sequence with a comma when it's going into the triplestore?

For example:

`http://iiif.museum.colby.edu/image/x/full/512 % comma % /0/default.jpg`  and replace ` % comma % ` with `,`

**Comment by cbutcosk** [comment]
(I'm traveling so please excuse my brevity here...)

1) This issue is a good reason to map our IIIF image identifier according to the pattern outlined in #12 :
```
<IIIF_URL> a crm:E38_Image ;
    rdfs:label "Label" ;
    dcterms:conformsTo <http://iiif.io/api/image> .
```

2) @caknoblock / @bsnikhila Can you verify that David's percent-encoding solution above (ie, my emitting the URI as `https://iiif.museum.colby.edu/image/NNN/full/512%2C/0/default.jpg`) also causes this bug? Because...

3) We have other image URLs (mentioned in #24 ) that pass percent encoded spaces just fine, but this full-res fix breaks those at the moment (rendering `http://embark.colby.edu:8080/Previews/embark/Lo%20Res%20and%20FMs/NNN_fm.jpg` as `http://embark.colby.edu:8080/Previews/full/Lo%20Res%20and%20FMs/NNN_fm.jpg`). But..

4) What is the timeframe on "short term" here? Exposing those URLs as full-res creates some insoluble issues for the museum (primarily rights on reproductions of 20th/21st century artworks, but technical ones too). A month is fine. If we're talking a year, I should just return our data to emitting the small `http://embark.colby.edu:8080...` URLs for those objects and map the IIIF identifier as in #12  .

edit: typos

**Comment by caknoblock** [comment]
Hopefully, we will have a general fix for this within a month.  Once we know what needs to be changed, I can estimate how long it will take.

**Comment by cbutcosk** [comment]
Looks like @bsnikhila worked around this in a recent mapping. Thanks all!
