### ISSUE TITLE
Map URIs under CCMA root domain

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#32]
I mentioned this to Craig over email, so just popping this here so we know it's open:

At Colby we finally got the root domain redirection working so this needs to be reflected in the mapping--the branded root domain is `http://data.museum.colby.edu/aac/`.

**Comment by cbutcosk** [comment]
Probably too late to be useful, but pinging this again. If you [query](http://data.americanartcollaborative.org/sparql?query=DESCRIBE+%3Chttp%3A%2F%2Fdata.museum.colby.edu%2Faac%2Fobject%2F8757%3E) for CCMA objects over SPARQL,  the triples show the right hostname, but Pubby does not return data if you visit [the page for that object](http://data.museum.colby.edu/aac/object/8757).

**Comment by kateblanch** [comment]
I'm not sure if this is the precise reason why this is happening - but it could be caused by the DNS redirect you have set up. The redirect has to not only redirect from data.museum.colby.edu/aac --> data.americanartcollaborative.org, it has to redirect each object URI - e.g. data.museum.colby.edu/aac/object/8757 --> http://data.americanartcollaborative.org/page/ccma/object/8757.

The other complication is that Pubby can't resolve more than 1 root domain, so as an added roadblock to testing, even if your DNS redirect from data.museum.colby.edu/aac/ --> data.americanartcollaborative.org/ccma works great, Pubby will return a 404.

Sorry to add complications to this bug - if there's any way you can look into DNS redirection at least that's a starting point. Grrrr!

**Comment by kateblanch** [comment]
Or, as Craig suggested - just move your data to your own SPARQL endpoint now and forgo the redirect drama :)!

**Comment by workergnome** [comment]
(Though, as Craig continually fails to mention, that will also mean that it is removed from the Browse app.)

**Comment by caknoblock** [comment]
Not true!  We will continue to load the data into our sparql endpoint as well, so it will be available in both place in the browse app.  It is just that the URL redirection will go to the museum endpoint instead of ours.  We have even configured our load scripts so that if the museums are hosting their own rdf repository, we can load from there instead of ours.
Craig

**Comment by workergnome** [comment]
Oh, lovely!  I was unaware of that.  That makes this a much more attractive option for people.

**Comment by cbutcosk** [comment]
TBH if I'm rolling my own to fix this, something statically-generated under `object/<id>[.html|.json|.ttl]` seems like a saner default. No reason to inflict Pubby on future folks. :)

**Comment by caknoblock** [comment]
You are only redirecting your individual object URIs, not generating the pages.  We do that on our server once you re-direct.  But if you want to serve your own pages, you can do that by hosting your own endpoint and not doing any redirection.  I think pubby is the simplest way to do that, but it certainly is not required.

**Comment by kateblanch** [comment]
@cbutcosk - Craig and team are trying to fix the larger Pubby issue. Apparently there is a code-bit that might be able to be extended to fix this. Let's see how that effort turns out, before you look to work arounds.

**Comment by cbutcosk** [comment]
Cool, checked this morning and it looks like the Pubby issue on ISI's side was resolved. Thanks @caknoblock et al!
